setTypePlanets(int type) {
  switch (type) {
    case 1:
      return "Tatooine";
    case 2:
      return "Tatooine";
    case 4:
      return "Tatooine";
    case 6:
      return "Tatooine";
    case 7:
      return "Tatooine";
    case 8:
      return "Tatooine";
    case 9:
      return "Tatooine";
    case 11:
      return "Tatooine";
    case 43:
      return "Tatooine";
    case 62:
      return "Tatooine";
    case 5:
      return "Alderaan";
    case 68:
      return "Alderaan";
    case 81:
      return "Alderaan";
    case 26:
      return "Bespin";
    case 30:
      return "Endor";
    case 3:
      return "Naboo";
    case 21:
      return "Naboo";
    case 35:
      return "Naboo";
    case 36:
      return "Naboo";
    case 37:
      return "Naboo";
    case 38:
      return "Naboo";
    case 39:
      return "Naboo";
    case 42:
      return "Naboo";
    case 60:
      return "Naboo";
    case 61:
      return "Naboo";
    case 66:
      return "Naboo";
    case 34:
      return "Coruscantv";
    case 55:
      return "Coruscantv";
    case 74:
      return "Coruscantv";
    case 22:
      return "Kamino";
    case 72:
      return "Kamino";
    case 73:
      return "Kamino";
    default:
      return "Unspecified";
  }
}
